# Generated by Django 2.2.16 on 2023-05-18 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20230510_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(choices=[('#09db4f', 'Зеленый'), ('#fa6a02', 'Оранжевый'), ('#b813d1', 'Фиолетовый')], help_text='Выберите цвет', max_length=7, unique=True, verbose_name='Название цвета "HEX"'),
        ),
    ]
